version: '3'

services:
   gsa-pg:
    image: bitnami/posgresql
    ports: 
     - 5432:5432
    environment: 
    - POSTGRESQL_USERNAME=docker
    - POSTGRESQL_PASSWORD=docker
    - POSTGRESQL_DATABASE=apisolid
  